# Generated by Django 5.2 on 2025-06-07 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Facebook', models.URLField(blank=True, null=True)),
                ('You_Tube', models.URLField(blank=True, null=True)),
                ('Instagram', models.URLField(blank=True, null=True)),
                ('Twitter', models.URLField(blank=True, null=True)),
                ('Linkden', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
