# Generated by Django 5.1.5 on 2025-06-06 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(blank=True, choices=[('Complete Blood Count (CBC)', 'Complete Blood Count (CBC)'), ('Blood Sugar - Fasting', 'Blood Sugar - Fasting'), ('Blood Sugar - Postprandial', 'Blood Sugar - Postprandial'), ('HbA1c (Glycated Hemoglobin)', 'HbA1c (Glycated Hemoglobin)'), ('Liver Function Test (LFT)', 'Liver Function Test (LFT)'), ('Kidney Function Test (KFT)', 'Kidney Function Test (KFT)'), ('Lipid Profile', 'Lipid Profile'), ('Thyroid Profile (T3, T4, TSH)', 'Thyroid Profile (T3, T4, TSH)'), ('Uric Acid', 'Uric Acid'), ('Creatinine', 'Creatinine'), ('Blood Urea', 'Blood Urea'), ('Serum Electrolytes (Na, K, Cl)', 'Serum Electrolytes (Na, K, Cl)'), ('Serum Bilirubin', 'Serum Bilirubin'), ('ALT/SGPT', 'ALT/SGPT'), ('AST/SGOT', 'AST/SGOT'), ('ALP (Alkaline Phosphatase)', 'ALP (Alkaline Phosphatase)'), ('Urine Routine Test', 'Urine Routine Test'), ('Stool Routine Test', 'Stool Routine Test'), ('Urine Culture & Sensitivity', 'Urine Culture & Sensitivity'), ('Stool Culture', 'Stool Culture'), ('Blood Culture', 'Blood Culture'), ('Sputum AFB Test', 'Sputum AFB Test'), ('Widal Test', 'Widal Test'), ('HIV Antibody Test', 'HIV Antibody Test'), ('HBsAg (Hepatitis B)', 'HBsAg (Hepatitis B)'), ('HCV Antibody', 'HCV Antibody'), ('CRP (C-Reactive Protein)', 'CRP (C-Reactive Protein)'), ('RA Factor', 'RA Factor'), ('ASO Titer', 'ASO Titer'), ('Dengue NS1 Antigen', 'Dengue NS1 Antigen'), ('Malaria Parasite', 'Malaria Parasite'), ('Typhoid IgM/IgG', 'Typhoid IgM/IgG'), ('Pregnancy Test (Urine HCG)', 'Pregnancy Test (Urine HCG)'), ('Peripheral Blood Smear', 'Peripheral Blood Smear'), ('Pap Smear', 'Pap Smear'), ('FNAC (Fine Needle Aspiration Cytology)', 'FNAC (Fine Needle Aspiration Cytology)'), ('Biopsy (Histopathology)', 'Biopsy (Histopathology)'), ('Vitamin D3', 'Vitamin D3'), ('Vitamin B12', 'Vitamin B12'), ('PSA (Prostate Specific Antigen)', 'PSA (Prostate Specific Antigen)'), ('CA-125 (Ovarian Cancer Marker)', 'CA-125 (Ovarian Cancer Marker)'), ('CEA (Carcinoembryonic Antigen)', 'CEA (Carcinoembryonic Antigen)'), ('FSH (Follicle Stimulating Hormone)', 'FSH (Follicle Stimulating Hormone)'), ('LH (Luteinizing Hormone)', 'LH (Luteinizing Hormone)'), ('Prolactin', 'Prolactin'), ('Testosterone', 'Testosterone'), ('Estradiol', 'Estradiol'), ('Insulin', 'Insulin'), ('Cortisol', 'Cortisol'), ('COVID-19 RT-PCR', 'COVID-19 RT-PCR')], max_length=200)),
                ('category', models.CharField(blank=True, choices=[('Biochemistry / Metabolic', 'Biochemistry / Metabolic'), ('Cardiology / Metabolic', 'Cardiology / Metabolic'), ('Hepatic / Biochemistry', 'Hepatic / Biochemistry'), ('Endocrinology', 'Endocrinology'), ('Nephrology', 'Nephrology'), ('Diabetes', 'Diabetes'), ('Hematology / Coagulation', 'Hematology / Coagulation'), ('Nutritional / Endocrinology', 'Nutritional / Endocrinology')], max_length=200)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('Description', models.TextField(blank=True, max_length=5000)),
                ('Lab_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.labmodel')),
            ],
        ),
    ]
