# Generated by Django 4.2.14 on 2025-05-04 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicemanagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicemanagement',
            name='price',
            field=models.DecimalField(choices=[('$40', '$40'), ('$30', '$30'), ('$40', '$40'), ('$30', '$30'), ('$40', '$40'), ('$30', '$30'), ('$40', '$40'), ('$30', '$30'), ('$40', '$40'), ('$30', '$30')], decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
