# Generated by Django 5.2 on 2025-05-05 09:06

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicemanagement', '0002_servicemanagement_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicemanagement',
            name='price',
            field=models.DecimalField(choices=[(Decimal('40.00'), '$40'), (Decimal('30.00'), '$30'), (Decimal('50.00'), '$50'), (Decimal('60.00'), '$60'), (Decimal('40.00'), '$40'), (Decimal('30.00'), '$30'), (Decimal('50.00'), '$50'), (Decimal('60.00'), '$60')], decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
