# Generated by Django 5.2 on 2025-05-09 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0001_initial'),
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='Full_name',
            new_name='Team_name',
        ),
        migrations.AddField(
            model_name='team',
            name='lab',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_member', to='lab.labmodel'),
        ),
    ]
