# Generated by Django 5.2 on 2025-05-28 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('team', '0004_team_team_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='Team_member',
            field=models.ManyToManyField(blank=True, null=True, to='accounts.account'),
        ),
    ]
