# Generated by Django 5.2 on 2025-05-07 07:31

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicemanagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_name', models.CharField(max_length=400, null=True)),
                ('Email', models.EmailField(max_length=600, unique=True)),
                ('Phone_Number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('Address', models.CharField(blank=True, max_length=200)),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], default='Male', max_length=200)),
                ('Appointment_Date', models.DateField(auto_now=True)),
                ('Payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=200)),
                ('Payment_option', models.CharField(choices=[('esewa', 'eSewa'), ('khalti', 'Khalti'), ('cod', 'Cash on Delivery')], default='eSewa', max_length=200)),
                ('Message', models.CharField(blank=True, max_length=3000)),
                ('Appointment_Booked', models.CharField(choices=[('Online', 'Online'), ('At_clinic', 'At clinic')], default='At clinic', max_length=200)),
                ('Amount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service', to='servicemanagement.servicemanagement')),
                ('Services', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicemgt', to='servicemanagement.servicemanagement')),
            ],
        ),
    ]
