# Generated by Django 5.1.5 on 2025-06-06 17:22

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_name', models.CharField(max_length=400, null=True)),
                ('Email', models.EmailField(max_length=600, unique=True)),
                ('Phone_Number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('Address', models.CharField(blank=True, max_length=200)),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], default='Male', max_length=200)),
                ('Appointment_Date', models.DateField()),
                ('Payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=200)),
                ('Payment_option', models.CharField(choices=[('esewa', 'eSewa'), ('khalti', 'Khalti'), ('cod', 'Cash on Delivery')], default='eSewa', max_length=200)),
                ('Message', models.CharField(blank=True, max_length=3000)),
                ('Total_price', models.PositiveIntegerField()),
                ('Appointment_Booked', models.CharField(choices=[('Online', 'Online'), ('At_clinic', 'At clinic')], default='At clinic', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
