# Generated by Django 5.2 on 2025-05-06 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingmodel',
            name='Appointment_Date',
            field=models.DateField(auto_now=True),
        ),
    ]
