# Generated by Django 5.1.5 on 2025-06-06 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0001_initial'),
        ('servicemanagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingmodel',
            name='Services',
            field=models.ManyToManyField(blank=True, related_name='servicemgt', to='servicemanagement.servicemanagement'),
        ),
    ]
