# Generated by Django 5.2 on 2025-06-07 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingmodel',
            name='Total_price',
        ),
    ]
