# Generated by Django 5.2 on 2025-05-26 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_bookingmodel_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingmodel',
            name='Amount',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
