# Generated by Django 5.1.5 on 2025-06-06 17:16

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LabModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Branch_name', models.CharField(blank=True, max_length=100, unique=True)),
                ('Email', models.EmailField(max_length=300, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, null=True, unique=True)),
                ('Phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, unique=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('lab_code', models.CharField(blank=True, editable=False, max_length=200)),
                ('lab_head', models.CharField(max_length=200)),
                ('latitude', models.DecimalField(decimal_places=6, default=0.0, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, default=0.0, max_digits=9)),
                ('Branch_type', models.CharField(blank=True, choices=[('Headquarter', 'Headquarter'), ('Other Branch', 'Sub Branch')], max_length=200)),
                ('capacity', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
