# Generated by Django 5.2 on 2025-05-04 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labmodel',
            name='lab_code',
            field=models.CharField(blank=True, editable=False, max_length=200),
        ),
    ]
