# Generated by Django 5.2 on 2025-05-06 07:21

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_alter_labmodel_lab_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labmodel',
            old_name='lab_name',
            new_name='Branch_name',
        ),
        migrations.AddField(
            model_name='labmodel',
            name='Branch_type',
            field=models.CharField(blank=True, choices=[('Headquarter', 'Headquarter'), ('Other Branch', 'other Branch')], max_length=200),
        ),
        migrations.AddField(
            model_name='labmodel',
            name='Email',
            field=models.EmailField(blank=True, max_length=300, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='labmodel',
            name='Phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
        migrations.AddField(
            model_name='labmodel',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='labmodel',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
        ),
    ]
