# Generated by Django 5.2 on 2025-05-07 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Banner/images/')),
                ('image_link', models.URLField(blank=True, null=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='Banner/images/')),
                ('video_link', models.URLField(blank=True, null=True)),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
